<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEBjxVqr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEBjxVqr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEBjxVqr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEBjxVqr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEBjxVqr\App_KernelDevDebugContainer([
    'container.build_hash' => 'EBjxVqr',
    'container.build_id' => '3e46acf0',
    'container.build_time' => 1674101734,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEBjxVqr');
