<?php

namespace ContainerTuzjB06;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_30wsQ3YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.30wsQ3Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.30wsQ3Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\DetalleRepository', 'getDetalleRepositoryService', true],
            'ventaRepository' => ['privates', 'App\\Repository\\VentaRepository', 'getVentaRepositoryService', true],
        ], [
            'productoRepository' => 'App\\Repository\\ProductoRepository',
            'repository' => 'App\\Repository\\DetalleRepository',
            'ventaRepository' => 'App\\Repository\\VentaRepository',
        ]);
    }
}
